name: alpaca
channels:
- conda-forge
- bioconda
- defaults
dependencies:
  - ca-certificates
  - gurobi::gurobi>=13.0.0
  - openssl
  - pandas
  - pyomo
  - scip
  - glpk
  - hatch
  - python=3.13.2
  - scipy
  - tqdm
  - r-base
  - bioconductor-genomicranges
  - r-jsonlite
  - r-optparse
