name: alpaca
channels:
- conda-forge
- bioconda
- defaults
dependencies:
  - ca-certificates
  - gurobi::gurobi>=13.0.0
  - openssl
  - pandas>=3.0.0
  - pyomo
  - scip
  - glpk
  - hatch
  - python=3.13.2
  - scipy
  - tqdm
  - r-base
  - bioconductor-genomicranges
  - r-jsonlite
  - r-optparse
  - seaborn
  - plotly
  - networkx
  - ipykernel
  - nbformat
  - python-kaleido
  - urllib3
